name: Deploy

on:
  push:
    tags:        
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 
          bundler-cache: true

      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        working-directory: ./android
        run: chmod +x gradlew

      - name: Install bundle
        working-directory: ./android/fastlane
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Configure Keystore
        working-directory: ./android
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/wollok-mobile.keystore
          echo "MYAPP_RELEASE_STORE_FILE=wollok-mobile.keystore" >> keystores/release.keystore.properties
          echo "MYAPP_RELEASE_KEY_ALIAS=$KEYSTORE_KEY_ALIAS" >> keystores/release.keystore.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=$KEYSTORE_STORE_PASSWORD" >> keystores/release.keystore.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=$KEYSTORE_KEY_PASSWORD" >> keystores/release.keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.KEYSTORE_STORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Create Google Play Config file
        working-directory: ./android
        run : |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.GOOGLE_CONFIG_JSON }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Distribute app to Google Play's internal track 🚀
        working-directory: ./android/fastlane
        run: bundle exec fastlane deploy
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: update android versions!"
          commit_user_name: Deploy Action
