name: Deploy

on:
  push:
    tags:        
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Configure Keystore
        working-directory: android
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/wollok-mobile.keystore
          mkdir keystores
          echo "MYAPP_RELEASE_STORE_FILE=wollok-mobile.keystore" >> keystores/release.keystore.properties
          echo "MYAPP_RELEASE_KEY_ALIAS=$KEYSTORE_KEY_ALIAS" >> keystores/release.keystore.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=$KEYSTORE_STORE_PASSWORD" >> keystores/release.keystore.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=$KEYSTORE_KEY_PASSWORD" >> keystores/release.keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.KEYSTORE_STORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Create Google Play Config file
        working-directory: ./android
        run : |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.GOOGLE_CONFIG_JSON }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Deploy using Fastlane 🚀
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'deploy'
          subdirectory: 'android'     
     - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add android/app/build.gradle
          git commit -m "chore: version update" --no-verify
          git push https://$USERNAME:$REPO_KEY@github.com/uqbar-project/wollok-mobile.git
        env:
          REPO_KEY: ${{secrets.PAT}}
          USERNAME: github-actions[bot]

